### ISSUE TITLE
Option to send message on join if player is not registed

### ISSUE THREAD

**Issue by Derkades** [NamelessMC/Nameless-Plugin#50]

**Comment by iJustBlessed** [comment]
With support for https://www.spigotmc.org/resources/messageannouncer.5408/ For support for json message + that the delay is correct because if i set the message delay to 5 minutes will your plugin send a message but messageannouncer too... so that are 2 message's in 5 minute's.. And i dont want that

**Comment by Derkades** [comment]
1) I can't magically hook into every plugin, only plugins that have an api
2) This message is sent on join so I am not sure what you are talking about with "delay"
